/* ==========================================================================
   owner.js — Owner tools.

   This page never touches the live website. It loads whatever is currently in
   data.js, lets the owner edit it in a friendly form, and then hands back a
   brand new data.js file to download. The maintainer drops that file into the
   project and pushes it. Nothing here needs a server, a login or a password,
   because nothing here can change what the public sees.
   ========================================================================== */
(function(){
"use strict";
var esc = NM.esc;
var root = document.getElementById("owner");

/* working copies, so nothing is edited in place */
var S    = JSON.parse(JSON.stringify(window.SITE || {}));
var A    = JSON.parse(JSON.stringify(window.APPLY || {mode:"builtin", hostedUrl:"", hostedName:""}));
var NEWS = JSON.parse(JSON.stringify(window.NEWS || []));
var INV  = JSON.parse(JSON.stringify(window.INVENTORY || []));

var tab = "inventory";
var editing = null;
var pending = [];   /* resized photos waiting to be downloaded */

/* ---------- generate the new data.js ---------- */
function buildDataFile(){
  var stamp = new Date().toLocaleString();
  return "/* ==========================================================================\n"
    + "   data.js — generated by Owner tools on " + stamp + "\n"
    + "   Dealership details, announcements and inventory.\n"
    + "   Safe to edit by hand as well: it is ordinary JavaScript.\n"
    + "   ========================================================================== */\n\n"
    + "window.SITE = "      + JSON.stringify(S,    null, 2) + ";\n\n"
    + "window.APPLY = "     + JSON.stringify(A,    null, 2) + ";\n\n"
    + "window.NEWS = "      + JSON.stringify(NEWS, null, 2) + ";\n\n"
    + "window.INVENTORY = " + JSON.stringify(INV,  null, 2) + ";\n";
}
function downloadText(filename, content, type){
  var blob = new Blob([content], {type: type || "text/plain"});
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(function(){ URL.revokeObjectURL(url); }, 1000);
}

/* ---------- photos ---------- */
function slug(s){
  return String(s || "photo").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
function resize(file, cb){
  if(!/^image\//.test(file.type)){ cb(null); return; }
  var reader = new FileReader();
  reader.onerror = function(){ NM.toast("That file could not be read."); cb(null); };
  reader.onload = function(){
    var img = new Image();
    img.onerror = function(){ NM.toast("That image could not be opened."); cb(null); };
    img.onload = function(){
      var max = 1400, w = img.width, h = img.height;
      if(w > max || h > max){ var r = Math.min(max/w, max/h); w = Math.round(w*r); h = Math.round(h*r); }
      var c = document.createElement("canvas");
      c.width = w; c.height = h;
      var ctx = c.getContext("2d");
      ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, w, h);
      ctx.drawImage(img, 0, 0, w, h);
      c.toBlob(function(blob){ cb(blob); }, "image/jpeg", 0.72);
    };
    img.src = reader.result;
  };
  reader.readAsDataURL(file);
}
function addPhotos(files){
  var list = Array.prototype.slice.call(files);
  if(!list.length) return;
  var base = slug([editing.year, editing.make, editing.model].filter(Boolean).join("-") || editing.id || "vehicle");
  var startAt = (editing.photos || []).length;
  var done = 0;
  NM.toast("Resizing " + list.length + (list.length === 1 ? " photo\u2026" : " photos\u2026"));
  list.forEach(function(file, i){
    resize(file, function(blob){
      if(blob){
        var name = base + "-" + (startAt + i + 1) + ".jpg";
        editing.photos.push("assets/img/" + name);
        pending.push({name: name, blob: blob, url: URL.createObjectURL(blob)});
      }
      if(++done === list.length){ render(); NM.toast("Photos ready. Download them before you close this page."); }
    });
  });
}

/* ---------- small form helpers ---------- */
function input(key, label, width, target, attrs){
  var id = "in_" + key + "_" + Math.random().toString(36).slice(2, 6);
  return '<div class="f w' + width + '"><label for="' + id + '">' + esc(label) + "</label>"
    + '<input id="' + id + '" data-bind="' + target + ':' + key + '" value="'
    + esc(target === "site" ? (S[key] || "") : (editing ? editing[key] || "" : "")) + '" ' + (attrs || "") + "></div>";
}

/* ---------- inventory tab ---------- */
function inventoryTab(){
  if(editing) return vehicleEditor();
  var rows = INV.map(function(v){
    return '<div class="rowitem">'
      + (v.photos && v.photos[0] ? '<img class="thumb" src="' + esc(v.photos[0]) + '" alt="" onerror="this.style.visibility=\'hidden\'">' : '<div class="thumb"></div>')
      + '<div class="meta"><b>' + esc(NM.vname(v)) + "</b>"
        + "<span>" + esc([v.trim, v.stock ? "Stock " + v.stock : "", v.mileage ? NM.num(v.mileage) + " mi" : "", NM.money(v.price)].filter(Boolean).join(" \u00B7 ")) + "</span>"
        + "<span>" + esc(v.status === "sold" ? "Sold" : v.status === "pending" ? "Sale pending" : "Available")
          + " \u00B7 " + ((v.photos || []).length) + " photos</span></div>"
      + '<button class="btn btn-line btn-sm" data-edit="' + esc(v.id) + '">Edit</button>'
      + '<button class="btn btn-line btn-sm" data-del="' + esc(v.id) + '">Remove</button></div>';
  }).join("");
  return '<div style="margin-bottom:18px"><button class="btn btn-navy" id="addVehicle">Add a vehicle</button></div>'
    + (rows || '<div class="empty">No vehicles yet. Add your first one.</div>');
}
function vehicleEditor(){
  var v = editing;
  var photos = (v.photos || []).map(function(p, i){
    var local = pending.filter(function(x){ return "assets/img/" + x.name === p; })[0];
    return '<figure><img src="' + esc(local ? local.url : p) + '" alt="" onerror="this.style.opacity=.2">'
      + '<button data-rmphoto="' + i + '" aria-label="Remove photo ' + (i+1) + '">&times;</button></figure>';
  }).join("");
  return '<div class="form"><div class="fieldset">'
    + "<h2>" + (NM.vname(v) === "Vehicle" ? "New vehicle" : esc(NM.vname(v))) + "</h2>"
    + '<p class="note">Year, make, model and price are what buyers look at first.</p>'
    + '<div class="fields">'
      + input("id", "Stock number (also the page address)", 4, "veh")
      + input("year", "Year", 2, "veh", 'inputmode="numeric"')
      + input("make", "Make", 3, "veh")
      + input("model", "Model", 3, "veh")
      + input("trim", "Trim", 4, "veh")
      + input("vin", "VIN", 5, "veh")
      + input("mileage", "Mileage", 3, "veh", 'inputmode="numeric"')
      + input("price", "Price", 3, "veh", 'inputmode="numeric"')
      + input("payment", "Payment note", 3, "veh")
      + '<div class="f w3"><label for="ed_status">Status</label><select id="ed_status" data-bind="veh:status">'
        + ["available","pending","sold"].map(function(x){
            return '<option value="' + x + '"' + (v.status === x ? " selected" : "") + ">"
              + (x === "available" ? "Available" : x === "pending" ? "Sale pending" : "Sold") + "</option>";
          }).join("") + "</select></div>"
      + input("body", "Body style", 3, "veh")
      + input("color", "Exterior color", 3, "veh")
      + input("engine", "Engine", 3, "veh")
      + input("transmission", "Transmission", 3, "veh")
      + input("drivetrain", "Drivetrain", 3, "veh")
      + input("fuel", "Fuel", 3, "veh")
      + '<div class="f w12"><label for="ed_desc">Description</label>'
        + '<textarea id="ed_desc" data-bind="veh:description">' + esc(v.description || "") + "</textarea></div>"
    + "</div></div>"
    + '<div class="fieldset"><h2>Photos</h2>'
      + '<p class="note">Pick photos from your phone or computer. They are resized automatically. '
      + "After you save, download them and hand them to whoever maintains the site along with the data file.</p>"
      + '<input type="file" id="photoInput" accept="image/*" multiple>'
      + '<div class="photostrip">' + photos + "</div></div>"
    + '<div class="formfoot"><button class="btn btn-gold" id="saveVehicle">Done with this vehicle</button>'
      + '<button class="btn btn-line" id="cancelVehicle">Cancel</button></div></div>';
}

/* ---------- announcements tab ---------- */
function newsTab(){
  var rows = NEWS.map(function(n, i){
    return '<div class="rowitem"><div class="meta"><b>' + esc(n.title) + "</b><span>" + esc(n.when)
      + "</span><span>" + esc(n.body) + "</span></div>"
      + '<button class="btn btn-line btn-sm" data-newsup="' + i + '"' + (i === 0 ? " disabled" : "") + ">Move up</button>"
      + '<button class="btn btn-line btn-sm" data-newsdel="' + i + '">Remove</button></div>';
  }).join("");
  return '<div class="form" style="margin-bottom:20px"><div class="fieldset"><h2>Post an announcement</h2>'
    + '<div class="fields">'
      + '<div class="f w3"><label for="nw_when">Date</label><input id="nw_when" placeholder="March 4"></div>'
      + '<div class="f w9"><label for="nw_title">Headline</label><input id="nw_title" placeholder="Three trucks just came in"></div>'
      + '<div class="f w12"><label for="nw_body">Details</label><textarea id="nw_body"></textarea></div>'
    + '</div></div><div class="formfoot"><button class="btn btn-navy" id="addNews">Post it</button></div></div>'
    + (rows || '<div class="empty">No announcements yet.</div>');
}

/* ---------- dealership tab ---------- */
function siteTab(){
  var hours = (S.hours || []).map(function(h, i){
    return '<div class="f w6"><label for="hr_' + i + '">' + esc(h.d) + "</label>"
      + '<input id="hr_' + i + '" data-hour="' + i + '" value="' + esc(h.h) + '"></div>';
  }).join("");
  var socials = (S.socials || []).map(function(x, i){
    return '<div class="f w6"><label for="so_' + i + '">' + esc(x.label) + " link</label>"
      + '<input id="so_' + i + '" data-social="' + i + '" value="' + esc(x.url) + '" placeholder="https://"></div>';
  }).join("");
  return '<div class="form">'
    + '<div class="fieldset"><h2>Name and pitch</h2><div class="fields">'
      + input("name", "Dealership name", 6, "site") + input("subtitle", "Line under the name", 6, "site")
      + '<div class="f w12"><label for="st_tag">Homepage headline</label><input id="st_tag" data-bind="site:tagline" value="' + esc(S.tagline || "") + '"></div>'
      + '<div class="f w12"><label for="st_lede">Homepage paragraph</label><textarea id="st_lede" data-bind="site:lede">' + esc(S.lede || "") + "</textarea></div>"
      + '<div class="f w12"><label for="st_about">About the dealership</label><textarea id="st_about" data-bind="site:about">' + esc(S.about || "") + "</textarea></div>"
    + "</div></div>"
    + '<div class="fieldset"><h2>Address and contact</h2>'
      + '<p class="note">Every directions button on the site is built from this address.</p><div class="fields">'
      + input("street", "Street address", 6, "site") + input("city", "City", 3, "site")
      + input("state", "State", 3, "site") + input("zip", "ZIP", 3, "site")
      + input("phone", "Phone", 4, "site") + input("email", "Email", 5, "site")
    + "</div></div>"
    + '<div class="fieldset"><h2>Hours</h2><div class="fields">' + hours + "</div></div>"
    + '<div class="fieldset"><h2>Social links</h2><p class="note">Leave one blank to hide it.</p>'
      + '<div class="fields">' + socials + "</div></div>"
    + '<div class="fieldset"><h2>Where the Apply buttons go</h2>'
      + '<p class="note">Leave this alone unless your maintainer tells you to change it.</p><div class="fields">'
      + '<div class="f w4"><label for="ap_mode">Application</label><select id="ap_mode" data-apply="mode">'
        + '<option value="builtin"' + (A.mode === "builtin" ? " selected" : "") + ">Form built into this site</option>"
        + '<option value="hosted"' + (A.mode === "hosted" ? " selected" : "") + ">Lender's secure application</option>"
        + "</select></div>"
      + '<div class="f w8"><label for="ap_url">Lender application link</label>'
        + '<input id="ap_url" data-apply="hostedUrl" value="' + esc(A.hostedUrl || "") + '" placeholder="https://"></div>'
    + "</div></div></div>";
}

/* ---------- shell ---------- */
function render(){
  var tabs = [["inventory","Inventory"],["news","Announcements"],["site","Dealership info"]].map(function(t){
    return '<button data-tab="' + t[0] + '" aria-selected="' + (tab === t[0]) + '">' + t[1] + "</button>";
  }).join("");
  var body = tab === "inventory" ? inventoryTab() : tab === "news" ? newsTab() : siteTab();
  root.innerHTML = '<div class="notice"><b>Nothing here changes the live website by itself.</b> '
      + "Make your changes, press <b>Download the updated data file</b>, then send that file "
      + "(and any photos) to whoever maintains the site. Keep this tab open until you have downloaded everything.</div>"
    + '<div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px">'
      + '<button class="btn btn-gold" id="dlData">Download the updated data file</button>'
      + (pending.length ? '<button class="btn btn-navy" id="dlPhotos">Download ' + pending.length + " new photo" + (pending.length === 1 ? "" : "s") + "</button>" : "")
      + '<a class="btn btn-line" href="index.html">View the site</a>'
    + "</div>"
    + '<div class="tabs">' + tabs + "</div>" + body;
}

/* ---------- events ---------- */
root.addEventListener("input", function(e){
  var t = e.target;
  var bind = t.getAttribute("data-bind");
  if(bind){
    var parts = bind.split(":");
    if(parts[0] === "site") S[parts[1]] = t.value;
    else if(editing) editing[parts[1]] = t.value;
    return;
  }
  if(t.hasAttribute("data-hour"))   { S.hours[Number(t.getAttribute("data-hour"))].h = t.value; return; }
  if(t.hasAttribute("data-social")) { S.socials[Number(t.getAttribute("data-social"))].url = t.value; return; }
  if(t.hasAttribute("data-apply"))  { A[t.getAttribute("data-apply")] = t.value; return; }
});
root.addEventListener("change", function(e){
  var t = e.target;
  if(t.id === "photoInput"){ addPhotos(t.files); return; }
  if(t.id === "ed_status" && editing){ editing.status = t.value; return; }
  if(t.hasAttribute("data-apply")){ A[t.getAttribute("data-apply")] = t.value; return; }
});
root.addEventListener("click", function(e){
  var t = e.target;
  if(!t.closest) return;
  var el;

  if((el = t.closest("[data-tab]"))){ tab = el.getAttribute("data-tab"); editing = null; render(); return; }

  if(t.id === "addVehicle"){
    editing = {id:"", stock:"", year:"", make:"", model:"", trim:"", vin:"", mileage:"", price:"", payment:"",
               body:"", color:"", engine:"", transmission:"", drivetrain:"", fuel:"",
               status:"available", description:"", photos:[]};
    render(); return;
  }
  if((el = t.closest("[data-edit]"))){
    var found = INV.filter(function(v){ return v.id === el.getAttribute("data-edit"); })[0];
    editing = JSON.parse(JSON.stringify(found)); render(); return;
  }
  if((el = t.closest("[data-del]"))){
    var id = el.getAttribute("data-del");
    var veh = INV.filter(function(v){ return v.id === id; })[0];
    if(confirm("Remove " + NM.vname(veh) + " from the inventory?")){
      INV = INV.filter(function(v){ return v.id !== id; }); render();
    }
    return;
  }
  if(t.id === "saveVehicle"){
    if(!String(editing.id || "").trim()){ NM.toast("Give it a stock number first."); return; }
    editing.id = String(editing.id).trim().replace(/\s+/g, "-");
    editing.stock = editing.stock || editing.id;
    var at = -1;
    INV.forEach(function(v, i){ if(v.id === editing.id) at = i; });
    if(at > -1) INV[at] = editing; else INV.unshift(editing);
    editing = null; render(); NM.toast("Saved. Download the data file when you are finished."); return;
  }
  if(t.id === "cancelVehicle"){ editing = null; render(); return; }
  if((el = t.closest("[data-rmphoto]"))){ editing.photos.splice(Number(el.getAttribute("data-rmphoto")), 1); render(); return; }

  if(t.id === "addNews"){
    var title = document.getElementById("nw_title").value.trim();
    if(!title){ NM.toast("Give the announcement a headline."); return; }
    NEWS.unshift({when: document.getElementById("nw_when").value.trim() || "Today",
                  title: title, body: document.getElementById("nw_body").value.trim()});
    render(); return;
  }
  if((el = t.closest("[data-newsdel]"))){ NEWS.splice(Number(el.getAttribute("data-newsdel")), 1); render(); return; }
  if((el = t.closest("[data-newsup]"))){
    var i = Number(el.getAttribute("data-newsup"));
    if(i > 0){ var tmp = NEWS[i-1]; NEWS[i-1] = NEWS[i]; NEWS[i] = tmp; render(); }
    return;
  }

  if(t.id === "dlData"){ downloadText("data.js", buildDataFile(), "text/javascript"); return; }
  if(t.id === "dlPhotos"){
    pending.forEach(function(ph, i){
      setTimeout(function(){
        var a = document.createElement("a");
        a.href = ph.url; a.download = ph.name;
        document.body.appendChild(a); a.click(); a.remove();
      }, i * 400);
    });
    NM.toast("Saving " + pending.length + " photo" + (pending.length === 1 ? "" : "s") + " to your downloads folder.");
    return;
  }
});

window.addEventListener("beforeunload", function(e){
  if(pending.length){ e.preventDefault(); e.returnValue = ""; }
});

render();
})();
